### ISSUE TITLE
Can't execute the PC tool on Linux

### ISSUE THREAD

**Issue by zenaror** [GMMan/xros-loader-code-crown-tools#1]
Hi!

Since I don't have the SD informations to use as parameter via Windows (can only use CodeCrownTool.Console... CodeCrownTool don't exist). I don't know how to find the CID, CSD and SSR of my card.
So, I decide to try using Ubuntu (22.04 LTS). But the terminal didn't recgonize the "CodeCrownTool" as a command (or file)

Is this really possible to run using Ubuntu? Or the README is outdated?

I tried to use at the end .PDB, .DLL, .EXE... any command works

**Comment by GMMan** [comment]
You need to have .NET Core 3.1 runtime to run things. If the build doesn't work on Linux, build it from source.

**Comment by zenaror** [comment]
> You need to have .NET Core 3.1 runtime to run things. If the build doesn't work on Linux, build it from source.

I have the .net core 3.1 on windows ok.. It works fine... Except the extra parameters to run. I can't find that for my sd card... (But still needs to use the .console at the end)

On Linux I installed the .net core via script (from MS site)
I'll try build again from source.. This time from Linux directly...

But I copied the build that I made on windows to my Linux, and didn't work

**Comment by zenaror** [comment]
> 

I tried rebuild everything again... But no success... Still getting the same issue

**Comment by GMMan** [comment]
What output are you actually getting?

**Comment by zenaror** [comment]
> What output are you actually getting?

Basically, a some DLLs, JSON, PDB and a .EXE file named "CodeCrownTool.Console.exe", Any of these files my Ubuntu can execute

If it's possible to get the CID, CSD and SSR via Windows using some third-party programm for example, can you tell me how?

**Comment by GMMan** [comment]
Could you post a screenshot of how you're running it?

There's no easy way of getting the registers on Windows because there's no unified interface for getting them, so if you want to do so on Windows, you'll need to figure out how yourself.

**Comment by zenaror** [comment]
> Could you post a screenshot of how you're running it?

Sure! here!
I'm using Xbuild to compile
https://ibb.co/zZTXF5K
https://ibb.co/XVQwGrb
https://ibb.co/8PmKgFM

> There's no easy way of getting the registers on Windows because there's no unified interface for getting them, so if you want to do so on Windows, you'll need to figure out how yourself.

Oh, got it! No problem =)

**Comment by GMMan** [comment]
You should be able to just use `dotnet build` to compile after you've installed .NET Core SDK.

**Comment by zenaror** [comment]
> You should be able to just use `dotnet build` to compile after you've installed .NET Core SDK.

Good News! Apparently everything works now! But only works using the Ubuntu 20.04 (the 22.04 didn't work for now with me)

(in case if you want to update the readme, this is the steps what I follow to build the program. Could be useful for novice users)

First I install the .net core 3.1 using these commands:
- wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
- sudo dpkg -i packages-microsoft-prod.deb
- sudo apt update 
- sudo apt install apt-transport-https 
- sudo apt install dotnet-sdk-3.1
- sudo apt install dotnet-runtime-3.1 

Then I run this command just to make sure that's the correct version
- dotnet --version

Then I entered in the CodeCrownTool folder and run the `dotnet build` to compile and enter in the folder `CodeCrownTool.Console\bin\Debug\netcoreapp3.1` and than run `./CodeCrownTool.Console` and now it shows some infos about the commands, like the Windows Build did when I simply open the .EXE file

I'll get some SD cards now and use my built-in SD reader from my laptop to test!

Thanks so much @GMMan !

**Comment by zenaror** [comment]
@GMMan  can you help me with one more thing?

I made your Arduino setup here and manage to get work 2 SD cards here.
But now I'm stuck in the PC tool ...
I got the CID, CSD and SSR from the Arduino Console and tried to pass as a parameter in the CodeCrownTool.Console.

I'm using something like this: CodeCrownTool.Console verify E:\ --cid XXXXXX --csd YYYYYY --ssr ZZZZZZ
But immediately the console returns to me the message  (the same applys if I change the order)
"Specify --help for a list of available options and commands.
Unrecognized option '--cid'"

Is the command right?

**Comment by GMMan** [comment]
The arguments are a bit weird, CID, CSD, and SSR are global options, and the command line parser needs them to go before the verb.

**Comment by zenaror** [comment]
So... it needs to be something like this?

`CodeCrownTool.Console --cid XXXXXX --csd YYYYYY --ssr ZZZZZZ verify E:\` ?
