### ISSUE TITLE
Problem using the tool

### ISSUE THREAD

**Issue by Rinx64** [GMMan/xros-loader-code-crown-tools#2]
I just can't use the tool and I don't know what the problem is, maybe there's missing data, maybe my computer just doesn't work, that's why I'm looking for help and there to solve the problem and I would be very grateful if I could use both tools myself

**Comment by GMMan** [comment]
First question is what are you trying to accomplish, and what have you tried?

**Comment by Rinx64** [comment]
I've already seen that I might have to put the data in a folder somewhere
and I would just like to use it to create my own maps and make my own
digicrons

Yukai Li ***@***.***> schrieb am Mo., 20. Nov. 2023, 22:17:

**Comment by GMMan** [comment]
This program is designed to create Code Crowns from supported SD cards and allow loading and dumping map data, but does not facilitate the editing of map data.

**Comment by Rinx64** [comment]
That's not my problem, I can't even start the program and create anything
at all And that's why I wanted to ask, does he have any idea what the
problem could be? My PC is missing any data, do I need any special
programs?I don't have the problem with SD cards or something like that, I
hope

Yukai Li ***@***.***> schrieb am Mo., 20. Nov. 2023, 23:14:

**Comment by Rinx64** [comment]
The thing is that I can't even run the exe file properly and I'm really at
my wits' end I would be very happy if I got the problem solved and then I
can finally make my own digicrons

Rin Otaku ***@***.***> schrieb am Di., 21. Nov. 2023, 12:16:

**Comment by GMMan** [comment]
Again, what have you tried? How did you download and run the program? Are there any error messages?

**Comment by Rinx64** [comment]
I downloaded the program as normal from Google via the website and then
opened it in my folder as a file CodeCrownTool.exe And ran that on my PC
and nothing else has happened since then My question is if any files are
missing, I need special programs Or that I forgot to add something essential

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 16:03:

**Comment by GMMan** [comment]
It's a command-line program, so you need to run it in Command Prompt or PowerShell to see the output.

**Comment by Rinx64** [comment]
And with powershell I can do all of this and then all I have to do is enter
text, so to speak. Sorry that sounds so stupid, but I'm new to the genre

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 19:57:

**Comment by GMMan** [comment]
I suggest reading the [readme](https://github.com/GMMan/xros-loader-code-crown-tools/blob/master/CodeCrownTool/README.md) so you know your options.

**Comment by Rinx64** [comment]
Yes, I've already read that but it didn't really help my problem

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 21:33:

**Comment by GMMan** [comment]
You should probably learn about using command-line programs first. There are plenty of tutorials you can find on Google.

**Comment by Rinx64** [comment]
Yes, that might not be the worst idea to go back to school and learn
everything from scratch and how to create such code. Thanks for the help
I'll make sure it's running before I do any major programming

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 21:38:

**Comment by Rinx64** [comment]
😊

Rin hat über Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
reagiert

Rin Otaku ***@***.***> schrieb am Di., 21. Nov. 2023, 22:17:

**Comment by GMMan** [comment]
It's not so much coding but just a different way of using some programs. It's useful to know.

**Comment by Rinx64** [comment]
If you're not stupid enough to ask, what other programs are needed to work
properly with the tool - most likely one for graphics too

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 22:42:

**Comment by GMMan** [comment]
There's no other program needed to work with the tool for the scope it's designed for, although you may need an Arduino Uno or Pi Pico if you want to set up the security sector for converting a regular SD card to a Code Crown. If you want to import/export official content to a Code Crown, this program will do that, but if you want to edit graphics or other content within a Code Crown data package, that requires knowledge of the data's format, which is not within the scope of this program.

**Comment by Rinx64** [comment]
So I just have the same thing again, I can create graphics on this card
myself and don't need any other programs, just knowledge of how to process
this data

Yukai Li ***@***.***> schrieb am Di., 21. Nov. 2023, 22:51:

**Comment by GMMan** [comment]
Of course you can do everything manually if you want, this is just to make the actual card management convenient. As previously mentioned, actually editing the contents of Code Crown data is not in the scope of this program.
