### ISSUE TITLE
No idea how to use this.

### ISSUE THREAD

**Issue by Jaykiro** [GMMan/xros-loader-code-crown-tools#3]
Hello,

I downloaded the V1.0.1 build release but I can't get it to work. The only thing I knew to try was opening the "CodeCrownTool.Console.exe" but whenever I would try, it would open the cmd for a split second, then close. I don't know what I'm doing wrong, but there wasn't exactly any info on if there was anything special I had to do. I don't know much about github programs or getting them to work properly so please excuse my ignorance in the matter. I'm on windows 10, 64-bit, if that helps.

Thanks,
Jayke.

**Comment by GMMan** [comment]
This is a command-line program, so you'll have to run it through a command prompt or PowerShell.

**Comment by Jaykiro** [comment]
How exactly does one do that? I went into my admin cmd, set the directory to the folder and used the "start CodeCrownTool.Console.exe" command, and it did the same thing.

**Comment by GMMan** [comment]
There's no need to use the `start` command. You should look up command line tutorials if you are not familiar with such environments.

**Comment by Jaykiro** [comment]
Right, I'll take a look into that. Sorry for bothering you, I'm sure you're probably sick of people complaining.

**Comment by Jaykiro** [comment]
I've taken a look and nothing I've found has helped much. Everywhere I looked pointed toward using the Start command, so I tried powershell instead and used the ".\CodeCrownTool.Console.exe" command, and it seemed to open it, but any time I try running a command with the usage example, it comes up with an error saying it doesn't recognise "CodeCrownTool" as a function.
![Screenshot 2023-12-11 090717](https://github.com/GMMan/xros-loader-code-crown-tools/assets/43959414/36e02550-ad76-4c36-94bc-b9e786cb20b5)

**Comment by GMMan** [comment]
`CodeCrownTool` in the examples represents the name of the program. I think I wrote that before splitting out the console program, so just substitute with the actual executable name as appropriate.

**Comment by Jaykiro** [comment]
Oh, so an example would be "CodeCrownTool.Console.exe list"?

**Comment by Jaykiro** [comment]
I worked out getting commands to actually work, but how to do find my SD's CID, CSR, and SSR?

**Comment by GMMan** [comment]
You can't really get it on Windows, so you'd need to get an Arduino Uno or Raspberry Pi Pico for creating the security sector.

**Comment by Jaykiro** [comment]
I see. That's unfortunate. Ok, well thanks for your help, I'll look into that a bit more.
